### ISSUE TITLE
msgpack-python is deprecated

### ISSUE THREAD

**Issue by kaolpr** [m-labs/microscope#2]
`msgpack-python` dependency is depracated and leads to coillisions when used with recent msgpack in Nix.

**Comment by sbourdeauducq** [comment]
Can you elaborate on what exactly is deprecated, and how to reproduce the "collisions"? What commands did you run and what error message is printed?

**Comment by kaolpr** [comment]
One of packages I need to use in my setup (that also includes ARTIQ) needs msgpack, however, `msgpack`, not `msgpack-python`, which is deprecated according to PyPI (https://pypi.org/project/msgpack-python/).
Trying to use both versions leads to collision. An issue is raised at nixpkgs repo: https://github.com/NixOS/nixpkgs/issues/48864

As a workaround I modified definition of `microscope` package: moved `msgpack-python` to `buildInputs` and replaced `msgpack-python` with `msgpack` in `propagatedBuildInputs`.

**Comment by sbourdeauducq** [comment]
> moved `msgpack-python` to `buildInputs`

Why is this one step necessary? Isn't the correct solution to just use ``msgpack`` instead of ``msgpack-python`` everywhere?

**Comment by kaolpr** [comment]
Would be great, but I think you would have to change that line: https://github.com/m-labs/microscope/blob/41c41206119b0d5463a93da52f21ffa771f87e26/setup.py#L33

**Comment by sbourdeauducq** [comment]
https://git.m-labs.hk/M-Labs/nix-scripts/commit/e4a803826df7bf671dc71558cf127ef6ba6372ac
